# Content of pipeline.yaml
tasks:
  - source: extract.py
    product:
      # scripts generate executed notebooks as outputs
      nb: output/extract.html
      # you can define as many outputs as you want
      data: data/raw.parquet

  - source: transform.py
    product: 
      nb: output/transform.html
      data: data/transformed.parquet